### ISSUE TITLE
Form validation

### ISSUE THREAD

**Issue by mbertuol** [edmundgentle/password#1]
Hello Edmund,

Thank you for publishing our plugin.

I am trying to implement the ckecklist. Is there a form to enable the "Save password" button only when all the items of the checklist are a pass?

Thank you,

Mauro

**Comment by edmundgentle** [comment]
My latest commit added a number of changes moving slightly further this way. You can do server side form validation if your element has a `name` attribute (eg. `password_field`), a hidden form element called `[NAME]_pass` is automatically created (eg. `password_field_pass`).

You can also do client-side validation using the `change` event. You can also use the new `calculate` method to work out the password score at any point:

```js
var score=$("#myPassword").password('calculate');
//returns an array with 3 parts, matching the change event return values
```

Regarding languages, only the checklist overwrites the native language. Other functionality, such as the strength indicator can be written in another language. And you can bypass the checklist by using the `change` event to produce the checklist yourself. Hope this helps!

Edmund
