### ISSUE TITLE
JSON dictionary match still returns passed == true

### ISSUE THREAD

**Issue by jheliker** [edmundgentle/password#6]
Thanks for the awesome library!

In the current version if I enter a password matching one of the JSON dictionary values, I see a problem listed "CONTAINS_COMMON_WORD", but passed is still "true".

Is this intended behavior? Seems to be a mistake if the dictionary is for disallowed values.

**Comment by edmundgentle** [comment]
Hi,

Thanks for using Password!

The `pass` variable is calculated based on the score. The default minimum score is `0.3` out of `1.0`, but you can adjust this by changing the `minAcceptableScore` setting. Some `issues` will force `pass` to be `false`, for example `TOO_SHORT` and `CONTAINS_SPACE` will always return `false` for `pass`.

(I've noticed a slight inconsistency, where the minimum score setting is from 0-1, but `pass` is out of 100. I'll try and fix this when I have some time!)

**Comment by edmundgentle** [comment]
Fixed the inconsistency in `minAcceptableScore` with latest push.
